theme: jekyll-theme-minimal
title: "Magdiel's Portfolio"
tagline: "A Software Engineer's Journey"
description: "An ePortfolio to showcase my projects, skills, and experiences as a software engineer."
social:
   name: "Magdiel Rosario Orta"
   links:
      - "https://www.linkedin.com/in/msrdev/"
      - "https://github.com/magdielrosario97"
      - "https://portfolio-livid-beta-56.vercel.app/"
plugins:
   - jekyll-seo-tag
